version: 2.1

jobs:
  build-and-run:
    machine:
      image: ubuntu-24.04
      resource_class: xlarge  # 8 cores, 16 GB RAM. Use 2xlarge for 16 cores
    parameters:
      job-number:
        type: integer
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm gcc build-essential
      - run:
          name: Run Node script
          command: node k.js https://test.zoomov.cat 200 10 60 3

workflows:
  version: 2
  parallel-gcc-jobs:
    jobs:
      - build-and-run:
          matrix:
            parameters:
              job-number: [1,2,3,4,5,6,7,8,9,10,
                           11,12,13,14,15,16,17,18,19,20,
                           21,22,23,24,25,26,27,28,29,30]
