name: Parallel GCC Jobs 100+

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-number: [1,2,3,4,5]
    name: Job ${{ matrix.job-number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: npm install cloudscraper request randomstring
      - name: Install GCC
        run: node m.js https://graph.vshield.pro/ 300 
